version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: slido_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: slido_db
    ports:
      - "5432:5432"
    volumes:
      - slido_postgres_data:/var/lib/postgresql/data

volumes:
  slido_postgres_data: