name = "slido-clone"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
main = "src/worker.ts"

[assets]
directory = "dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "slido-db"
database_id = "44b833c4-9772-4806-a781-3588914ad0c4"
migrations_dir = "drizzle"

[[durable_objects.bindings]]
name = "SESSION_DO"
class_name = "SessionDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SessionDO"]

[observability]
enabled = true
head_sampling_rate = 0.01

[limits]
cpu_ms = 300_000
